### PR TITLE
Upgrade esp-hal v0.16.1

### PR DESCRIPTION
**Pull request by LLFourn**
This allows us to drop the nightly toolchain. I deleted the toolchain.toml file.

One peculiar thing I had to do was lower the heap size to avoid some allocation failures. It would be really good to understand why this was necessary before merging.

Main benefit of this is that it seems to fix the problem of panic messages not being displayed in the panic handler. Note i'm not sure if that's to do with lowering the heap size or just the dependency upgrade.

This is on top of #117

### CODE REVIEW

**Comment by LLFourn** [comment]
I just pushed a commit to clean up display errors in `st7735.rs`. We need `error_print` to be infallible so we don't panic inside the panic handler.

**Comment by LLFourn** [comment]
@musdom do you have any idea why the heap size change was necessary?

**Comment by musdom** [comment]
Not sure. I tried flashing this 0.15 template https://github.com/esp-rs/esp-template and was able to give it 300kB no problem.

**Comment by nickfarrow** [comment]
Nice so many unwraps removed :broom:

Rebased and upgraded `hal` to `0.16.0` which notably makes `esp32c3` a feature rather than its own package.

Tested and reviewed. 

---

I could not figure out the cause of the memory allocation error.

I looked through the `hal` changelogs but nothing really stood out, couldnt quite understand https://github.com/esp-rs/esp-hal/pull/1289.

Tried finding which line the error was occurring on using panics. 
When using a 300kb heap size on a device that already has a key, the panic seems to be happening in this line `match flash.read_header()`, but I don't think there's anything of interest happening in here? Memory probably being exhausted elsewhere, i can keep looking

**Comment by LLFourn** [comment]
I'm pretty sure @musdom already discovered that it was changes to the display driver.

**Comment by nickfarrow** [comment]
Confirmed it seems to be SPI/display related. When using a 166+ byte heap, I am unable to allocate anything after intializing the display.

Haven't managed to figure out much more..

There are some things in the changelog which look interesting,
https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md
enabling `place-spi-driver-in-ram` seemed to have no effect.

I began to try the unreleased `esp-hal`, but didn't quite manage to build for our device, not sure if this avenue is worth exploring.

**Review by nickfarrow — APPROVED** [review]

**Pull request merged**
